---
development:
  cloud_name: phones
  api_key: '329153271254667'
  api_secret: <%= ENV["SECRET_KEY_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: phones
  api_key: '329153271254667'
  api_secret: <%= ENV["SECRET_KEY_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: phones
  api_key: '329153271254667'
  api_secret: <%= ENV["SECRET_KEY_CLOUDINARY"] %>
  enhance_image_tag: true
  static_image_support: false
