default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: phones_development
  username: <%= ENV["DEVELOPMENT_DB_USERNAME"] %>
  password: <%= ENV["DEVELOPMENT_DB_PASSWORD"] %>

test: &test
  <<: *default
  database: phones_test
  username: <%= ENV["DEVELOPMENT_DB_USERNAME"] %>
  password: <%= ENV["DEVELOPMENT_DB_PASSWORD"] %>

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV["PRODUCTION_DB_DATABASE"] %>
  pool: 5
  username: <%= ENV["PRODUCTION_DB_USERNAME"] %>
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>

cucumber:
  <<: *test

